<a href="https://colab.research.google.com/github/AsSakina/Code_Projects/blob/main/CheckP_APIs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Checkpoint Objective** :      

You have been given a task to gather data about movies from the Open Movie Database (OMDb) API and store it in a pandas dataframe. The data should include the movie title, year of release, director, and rating.

**Instructions** :      

Go to the OMDb API website (https://www.omdbapi.com/apikey.aspx) and obtain an API key.
Install the requests and pandas libraries if you have not already done so.
Use the requests library to send a request to the OMDb API to retrieve data about the top 10 movies.
Parse the data using the json library to extract the title, year, director, and rating for each movie.
Store the extracted data in a pandas dataframe with appropriate column names.
Print the dataframe to verify that the data has been successfully stored.
Note: The API key needs to be included in the request URL. The request URL for the top 10 movies is: http://www.omdbapi.com/?apikey=[YOUR_API_KEY]&s=*&type=movie&page=1. Replace [YOUR_API_KEY] with your actual API key.

Here is a tutorial on how to get an API key : tutorial (https://www.youtube.com/watch?v=UZtruL7svkc)

In [1]:
#Importing Libraries
#Install the requests and pandas libraries if you have not already done so.
import pandas as pd
import json
import requests

In [2]:
#Use the requests library to send a request to the OMDb API to retrieve data about the top 10 movies.
import requests
api_url = "http://www.omdbapi.com/?apikey=d2a0a307&s=Murder&type=movie&page=1."
response = requests.get(api_url)
data = response.json()
data

{'Search': [{'Title': 'Murder on the Orient Express',
   'Year': '2017',
   'imdbID': 'tt3402236',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk5OGFiYzktMTkwNS00ZjQ5LWFkNGQtNGM0MjA4MWE2MDIwXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_SX300.jpg'},
  {'Title': 'Memories of Murder',
   'Year': '2003',
   'imdbID': 'tt0353969',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BOGViNTg4YTktYTQ2Ni00MTU0LTk2NWUtMTI4OTc1YTM0NzQ2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg'},
  {'Title': 'Dial M for Murder',
   'Year': '1954',
   'imdbID': 'tt0046912',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BOWIwODIxYWItZDI4MS00YzhhLWE3MmYtMzlhZDIwOTMzZmE5L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg'},
  {'Title': 'Murder Mystery',
   'Year': '2019',
   'imdbID': 'tt1618434',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNTA2YTI5YjUtZWI4Zi00NWQ5LWFiYmEtOTBmNTUyNDAwNjllXkEyXkFqcGdeQXVyNjIzNzM4NzA@._V1_SX300.jpg'},
  {'Title': 'A Perfect Murder',
   'Year': '1998',
   'imdbID': 'tt0120787',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BZDZjN2M0YTMtOTM3MS00YTVkLTkwZWQtOTkzZGUwOGQzY2VhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg'},
  {'Title': 'Anatomy of a Murder',
   'Year': '1959',
   'imdbID': 'tt0052561',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMzM0MzE2ZTAtZTBjZS00MTk5LTg5OTEtNjNmYmQ5NzU2OTUyXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg'},
  {'Title': 'Murder on the Orient Express',
   'Year': '1974',
   'imdbID': 'tt0071877',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BNDlkZjJjYTktZDI4OS00MWFkLTg1MzMtNTY3MmI2OTBkMTU1XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg'},
  {'Title': 'Murder by Numbers',
   'Year': '2002',
   'imdbID': 'tt0264935',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMjljZTAwMGEtMzFiNS00NjIzLWFhYmQtNmE5YmJjNzRjYzJhXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_SX300.jpg'},
  {'Title': 'Murder Mystery 2',
   'Year': '2023',
   'imdbID': 'tt15255288',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMzkyMjU1ZjMtMDJlMS00M2YzLWJhZDQtYjFjZTUyMzI2MDViXkEyXkFqcGdeQXVyMzQyMDgzOTU@._V1_SX300.jpg'},
  {'Title': 'Manhattan Murder Mystery',
   'Year': '1993',
   'imdbID': 'tt0107507',
   'Type': 'movie',
   'Poster': 'https://m.media-amazon.com/images/M/MV5BMWM5MGZiZDAtMWE0Ny00MjY3LWJlOWItNjY4MmI4NDAyM2NhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg'}],
 'totalResults': '1811',
 'Response': 'True'}

In [3]:
dataset = pd.DataFrame.from_dict(data['Search'])
dataset

,Title,Year,imdbID,Type,Poster
0,Murder on the Orient Express,2017,tt3402236,movie,https://m.media-amazon.com/images/M/MV5BMTk5OG...
1,Memories of Murder,2003,tt0353969,movie,https://m.media-amazon.com/images/M/MV5BOGViNT...
2,Dial M for Murder,1954,tt0046912,movie,https://m.media-amazon.com/images/M/MV5BOWIwOD...
3,Murder Mystery,2019,tt1618434,movie,https://m.media-amazon.com/images/M/MV5BNTA2YT...
4,A Perfect Murder,1998,tt0120787,movie,https://m.media-amazon.com/images/M/MV5BZDZjN2...
5,Anatomy of a Murder,1959,tt0052561,movie,https://m.media-amazon.com/images/M/MV5BMzM0Mz...
6,Murder on the Orient Express,1974,tt0071877,movie,https://m.media-amazon.com/images/M/MV5BNDlkZj...
7,Murder by Numbers,2002,tt0264935,movie,https://m.media-amazon.com/images/M/MV5BMjljZT...
8,Murder Mystery 2,2023,tt15255288,movie,https://m.media-amazon.com/images/M/MV5BMzkyMj...
9,Manhattan Murder Mystery,1993,tt0107507,movie,https://m.media-amazon.com/images/M/MV5BMWM5MG...



---


- We can observe that **t** is more detailed than **s**

---
- In the following code, we create a list containing all the film titles in our dataset
- Then we create a new list film
- We perform an iteration with the for loop of our titles
- And we initialize article, which will contain all the names of the titles.
- We concatenate these with url
- We use a GET request that will be sent to a JSONPlaceholder
- The data in the response is in JSON format
- Then finally we use append to add all the elements in the list film initialised at debu

In [4]:
title = list(dataset['Title'])
film = []
for movie in title:
  article = f"t={movie}&type=movie&page=1" # input article
  url = "http://www.omdbapi.com/?apikey=d2a0a307&"+article
  response=requests.get(url)
  data = response.json()
  film.append(data)
film

[{'Title': 'Murder on the Orient Express',
  'Year': '2017',
  'Rated': 'PG-13',
  'Released': '10 Nov 2017',
  'Runtime': '114 min',
  'Genre': 'Crime, Drama, Mystery',
  'Director': 'Kenneth Branagh',
  'Writer': 'Michael Green, Agatha Christie',
  'Actors': 'Kenneth Branagh, Penélope Cruz, Willem Dafoe',
  'Plot': "When a murder occurs on the train on which he's travelling, celebrated detective Hercule Poirot is recruited to solve the case.",
  'Language': 'English, French, Arabic, German',
  'Country': 'United Kingdom, Malta, United States',
  'Awards': '2 wins & 25 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk5OGFiYzktMTkwNS00ZjQ5LWFkNGQtNGM0MjA4MWE2MDIwXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.5/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '61%'},
   {'Source': 'Metacritic', 'Value': '52/100'}],
  'Metascore': '52',
  'imdbRating': '6.5',
  'imdbVotes': '269,678',
  'imdbID': 'tt3402236',
  'Type': 'movie',
  'DVD': '27 Feb 2018',
  'BoxOffice': '$102,826,543',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Memories of Murder',
  'Year': '2003',
  'Rated': 'Not Rated',
  'Released': '02 May 2003',
  'Runtime': '132 min',
  'Genre': 'Crime, Drama, Mystery',
  'Director': 'Bong Joon Ho',
  'Writer': 'Bong Joon Ho, Kwang-rim Kim, Sung-bo Shim',
  'Actors': 'Song Kang-ho, Kim Sang-kyung, Roe-ha Kim',
  'Plot': 'In a small Korean province in 1986, two detectives struggle with the case of multiple young women being found raped and murdered by an unknown culprit.',
  'Language': 'Korean, English',
  'Country': 'South Korea',
  'Awards': '33 wins & 5 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BOGViNTg4YTktYTQ2Ni00MTU0LTk2NWUtMTI4OTc1YTM0NzQ2XkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.1/10'},
   {'Source': 'Metacritic', 'Value': '82/100'}],
  'Metascore': '82',
  'imdbRating': '8.1',
  'imdbVotes': '196,101',
  'imdbID': 'tt0353969',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$15,357',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Dial M for Murder',
  'Year': '1954',
  'Rated': 'PG',
  'Released': '29 May 1954',
  'Runtime': '105 min',
  'Genre': 'Crime, Thriller',
  'Director': 'Alfred Hitchcock',
  'Writer': 'Frederick Knott',
  'Actors': 'Ray Milland, Grace Kelly, Robert Cummings',
  'Plot': 'A former tennis star arranges the murder of his adulterous wife.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'Nominated for 1 BAFTA Award5 wins & 3 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BOWIwODIxYWItZDI4MS00YzhhLWE3MmYtMzlhZDIwOTMzZmE5L2ltYWdlXkEyXkFqcGdeQXVyNjc1NTYyMjg@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.2/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '90%'},
   {'Source': 'Metacritic', 'Value': '75/100'}],
  'Metascore': '75',
  'imdbRating': '8.2',
  'imdbVotes': '180,698',
  'imdbID': 'tt0046912',
  'Type': 'movie',
  'DVD': '29 Aug 2006',
  'BoxOffice': '$24,845',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Murder Mystery',
  'Year': '2019',
  'Rated': 'PG-13',
  'Released': '14 Jun 2019',
  'Runtime': '97 min',
  'Genre': 'Action, Comedy, Crime',
  'Director': 'Kyle Newacheck',
  'Writer': 'James Vanderbilt',
  'Actors': 'Adam Sandler, Jennifer Aniston, Luke Evans',
  'Plot': 'A New York cop and his wife go on a European vacation to reinvigorate the spark in their marriage, but end up getting framed and on the run for the death of an elderly billionaire.',
  'Language': 'English, French, Latin, Spanish',
  'Country': 'United States, Italy, Canada',
  'Awards': '1 win & 6 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BNTA2YTI5YjUtZWI4Zi00NWQ5LWFiYmEtOTBmNTUyNDAwNjllXkEyXkFqcGdeQXVyNjIzNzM4NzA@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.0/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '44%'},
   {'Source': 'Metacritic', 'Value': '38/100'}],
  'Metascore': '38',
  'imdbRating': '6.0',
  'imdbVotes': '156,890',
  'imdbID': 'tt1618434',
  'Type': 'movie',
  'DVD': '14 Jun 2019',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'A Perfect Murder',
  'Year': '1998',
  'Rated': 'R',
  'Released': '05 Jun 1998',
  'Runtime': '107 min',
  'Genre': 'Crime, Drama, Thriller',
  'Director': 'Andrew Davis',
  'Writer': 'Frederick Knott, Patrick Smith Kelly',
  'Actors': 'Michael Douglas, Gwyneth Paltrow, Viggo Mortensen',
  'Plot': 'A wealthy Wall Street speculator discovers that his wife has a lover. He investigates him and uses the carrot and stick to make him murder his wife. Planned to detail, it seems like a perfect murder.',
  'Language': 'English, Arabic',
  'Country': 'United States',
  'Awards': '2 wins & 3 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BZDZjN2M0YTMtOTM3MS00YTVkLTkwZWQtOTkzZGUwOGQzY2VhXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.6/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '55%'},
   {'Source': 'Metacritic', 'Value': '50/100'}],
  'Metascore': '50',
  'imdbRating': '6.6',
  'imdbVotes': '88,606',
  'imdbID': 'tt0120787',
  'Type': 'movie',
  'DVD': '30 Jun 2009',
  'BoxOffice': '$67,638,368',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Anatomy of a Murder',
  'Year': '1959',
  'Rated': 'Not Rated',
  'Released': '13 Jul 1959',
  'Runtime': '161 min',
  'Genre': 'Drama, Mystery',
  'Director': 'Otto Preminger',
  'Writer': 'Wendell Mayes, John D. Voelker',
  'Actors': 'James Stewart, Lee Remick, Ben Gazzara',
  'Plot': 'An upstate Michigan lawyer defends a soldier who claims he killed an innkeeper due to temporary insanity after the victim raped his wife. What is the truth, and will he win his case?',
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'Nominated for 7 Oscars. 12 wins & 19 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMzM0MzE2ZTAtZTBjZS00MTk5LTg5OTEtNjNmYmQ5NzU2OTUyXkEyXkFqcGdeQXVyNDY2MTk1ODk@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.0/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '100%'},
   {'Source': 'Metacritic', 'Value': '95/100'}],
  'Metascore': '95',
  'imdbRating': '8.0',
  'imdbVotes': '68,460',
  'imdbID': 'tt0052561',
  'Type': 'movie',
  'DVD': '11 Jul 2000',
  'BoxOffice': '$11,900,000',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Murder on the Orient Express',
  'Year': '2017',
  'Rated': 'PG-13',
  'Released': '10 Nov 2017',
  'Runtime': '114 min',
  'Genre': 'Crime, Drama, Mystery',
  'Director': 'Kenneth Branagh',
  'Writer': 'Michael Green, Agatha Christie',
  'Actors': 'Kenneth Branagh, Penélope Cruz, Willem Dafoe',
  'Plot': "When a murder occurs on the train on which he's travelling, celebrated detective Hercule Poirot is recruited to solve the case.",
  'Language': 'English, French, Arabic, German',
  'Country': 'United Kingdom, Malta, United States',
  'Awards': '2 wins & 25 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMTk5OGFiYzktMTkwNS00ZjQ5LWFkNGQtNGM0MjA4MWE2MDIwXkEyXkFqcGdeQXVyODY1NDk1NjE@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.5/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '61%'},
   {'Source': 'Metacritic', 'Value': '52/100'}],
  'Metascore': '52',
  'imdbRating': '6.5',
  'imdbVotes': '269,678',
  'imdbID': 'tt3402236',
  'Type': 'movie',
  'DVD': '27 Feb 2018',
  'BoxOffice': '$102,826,543',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Murder by Numbers',
  'Year': '2002',
  'Rated': 'R',
  'Released': '19 Apr 2002',
  'Runtime': '115 min',
  'Genre': 'Crime, Mystery, Thriller',
  'Director': 'Barbet Schroeder',
  'Writer': 'Tony Gayton',
  'Actors': 'Sandra Bullock, Ben Chaplin, Ryan Gosling',
  'Plot': 'Two gifted high school students execute a perfect murder - then become engaged in an intellectual contest with a seasoned homicide detective.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '2 nominations',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMjljZTAwMGEtMzFiNS00NjIzLWFhYmQtNmE5YmJjNzRjYzJhXkEyXkFqcGdeQXVyMTUzMDUzNTI3._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '6.1/10'},
   {'Source': 'Metacritic', 'Value': '50/100'}],
  'Metascore': '50',
  'imdbRating': '6.1',
  'imdbVotes': '60,170',
  'imdbID': 'tt0264935',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': '$31,945,749',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Murder Mystery 2',
  'Year': '2023',
  'Rated': 'PG-13',
  'Released': '31 Mar 2023',
  'Runtime': '90 min',
  'Genre': 'Action, Comedy, Crime',
  'Director': 'Jeremy Garelick',
  'Writer': 'James Vanderbilt',
  'Actors': 'Adam Sandler, Jennifer Aniston, Mark Strong',
  'Plot': 'Full-time detectives Nick and Audrey are struggling to get their private eye agency off the ground. They find themselves at the center of international abduction when their friend Maharaja, is kidnapped at his own lavish wedding.',
  'Language': 'English',
  'Country': 'United States',
  'Awards': '1 win',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMzkyMjU1ZjMtMDJlMS00M2YzLWJhZDQtYjFjZTUyMzI2MDViXkEyXkFqcGdeQXVyMzQyMDgzOTU@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '5.7/10'},
   {'Source': 'Metacritic', 'Value': '44/100'}],
  'Metascore': '44',
  'imdbRating': '5.7',
  'imdbVotes': '54,358',
  'imdbID': 'tt15255288',
  'Type': 'movie',
  'DVD': 'N/A',
  'BoxOffice': 'N/A',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'},
 {'Title': 'Manhattan Murder Mystery',
  'Year': '1993',
  'Rated': 'PG',
  'Released': '18 Aug 1993',
  'Runtime': '104 min',
  'Genre': 'Comedy, Mystery',
  'Director': 'Woody Allen',
  'Writer': 'Woody Allen, Marshall Brickman',
  'Actors': 'Woody Allen, Diane Keaton, Jerry Adler',
  'Plot': "A middle-aged couple suspects foul play when their neighbor's wife suddenly drops dead.",
  'Language': 'English',
  'Country': 'United States',
  'Awards': 'Nominated for 1 BAFTA Award4 nominations total',
  'Poster': 'https://m.media-amazon.com/images/M/MV5BMWM5MGZiZDAtMWE0Ny00MjY3LWJlOWItNjY4MmI4NDAyM2NhXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg',
  'Ratings': [{'Source': 'Internet Movie Database', 'Value': '7.3/10'},
   {'Source': 'Rotten Tomatoes', 'Value': '94%'},
   {'Source': 'Metacritic', 'Value': '71/100'}],
  'Metascore': '71',
  'imdbRating': '7.3',
  'imdbVotes': '45,504',
  'imdbID': 'tt0107507',
  'Type': 'movie',
  'DVD': '15 Dec 1998',
  'BoxOffice': '$11,330,911',
  'Production': 'N/A',
  'Website': 'N/A',
  'Response': 'True'}]



---


- now at the end we initialise dtf which will represent the conversion of our list into a dataframe


---

In [15]:
dtf = pd.DataFrame(film, columns = ['Title', 'Year', 'Director', 'imdbRating'])
dtf

                          Title  Year          Director imdbRating
0  Murder on the Orient Express  2017   Kenneth Branagh        6.5
1            Memories of Murder  2003      Bong Joon Ho        8.1
2             Dial M for Murder  1954  Alfred Hitchcock        8.2
3                Murder Mystery  2019    Kyle Newacheck        6.0
4              A Perfect Murder  1998      Andrew Davis        6.6
5           Anatomy of a Murder  1959    Otto Preminger        8.0
6  Murder on the Orient Express  2017   Kenneth Branagh        6.5
7             Murder by Numbers  2002  Barbet Schroeder        6.1
8              Murder Mystery 2  2023   Jeremy Garelick        5.7
9      Manhattan Murder Mystery  1993       Woody Allen        7.3